coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 75%
        threshold: 15%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

ignore:
  - "benches/**/*"
  - "tests/**/*"
  - "**/tests/**/*"
  - "**/*_test.rs"
  - "crates/rucket/src/main.rs"  # Binary entry point - integration tested
