#!/usr/bin/env bash
# Copyright 2026 Rucket Dev
# SPDX-License-Identifier: Apache-2.0

# S3 Compatibility Test Runner (using MinIO Mint)
# Usage: ./scripts/s3-compat-tests.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
REPORTS_DIR="$PROJECT_ROOT/target/s3-compat-reports"

# Default configuration
RUCKET_ENDPOINT="${RUCKET_ENDPOINT:-http://127.0.0.1:9000}"
RUCKET_ACCESS_KEY="${RUCKET_ACCESS_KEY:-rucket}"
RUCKET_SECRET_KEY="${RUCKET_SECRET_KEY:-rucket123}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

usage() {
    cat << EOF
S3 Compatibility Test Runner for Rucket (using MinIO Mint)

Usage: $0 [OPTIONS]

Options:
  -e, --endpoint URL    Rucket endpoint (default: $RUCKET_ENDPOINT)
  -a, --access-key KEY  Access key (default: $RUCKET_ACCESS_KEY)
  -s, --secret-key KEY  Secret key (default: $RUCKET_SECRET_KEY)
  -h, --help            Show this help message

Environment Variables:
  RUCKET_ENDPOINT       Rucket S3 endpoint URL
  RUCKET_ACCESS_KEY     S3 access key
  RUCKET_SECRET_KEY     S3 secret key

Examples:
  $0                                    # Run against local Rucket
  $0 --endpoint http://localhost:9000   # Custom endpoint

Reports are saved to: $REPORTS_DIR

Requirements:
  - Docker or Podman
  - Rucket must be running before executing tests
EOF
    exit 0
}

check_dependencies() {
    if ! command -v docker &> /dev/null && ! command -v podman &> /dev/null; then
        log_error "Neither docker nor podman found. Please install one of them."
        log_info "  Ubuntu/Debian: sudo apt install docker.io"
        log_info "  macOS: brew install docker"
        log_info "  Fedora: sudo dnf install podman"
        exit 1
    fi
}

check_rucket_running() {
    log_info "Checking if Rucket is running at $RUCKET_ENDPOINT..."

    if curl -s --connect-timeout 5 "$RUCKET_ENDPOINT" > /dev/null 2>&1; then
        log_success "Rucket is running at $RUCKET_ENDPOINT"
        return 0
    else
        log_error "Cannot connect to Rucket at $RUCKET_ENDPOINT"
        log_info "Please start Rucket first: cargo run --release -- serve"
        exit 1
    fi
}

setup_directories() {
    mkdir -p "$REPORTS_DIR"
}

# Detect container runtime (prefer docker, fallback to podman)
get_container_runtime() {
    if command -v docker &> /dev/null; then
        echo "docker"
    elif command -v podman &> /dev/null; then
        echo "podman"
    fi
}

run_mint_tests() {
    local runtime
    runtime=$(get_container_runtime)
    log_info "Using container runtime: $runtime"

    local results_file="$REPORTS_DIR/mint-results.json"
    local log_file="$REPORTS_DIR/mint-tests.log"

    # Parse endpoint
    local server_endpoint is_https
    if [[ "$RUCKET_ENDPOINT" =~ ^https:// ]]; then
        is_https="1"
        server_endpoint="${RUCKET_ENDPOINT#https://}"
    else
        is_https="0"
        server_endpoint="${RUCKET_ENDPOINT#http://}"
    fi

    # Pull latest mint image
    log_info "Pulling minio/mint image..."
    $runtime pull minio/mint:latest 2>/dev/null || true

    log_info "Running MinIO Mint S3 compatibility tests..."
    log_info "  Endpoint: $server_endpoint"
    log_info "  HTTPS: $is_https"
    log_info "  Mode: core"

    # Create a temporary directory for logs
    local mint_log_dir
    mint_log_dir=$(mktemp -d)

    # Run mint container
    # Note: We use --network=host to access localhost endpoints
    local exit_code=0
    if timeout 1800 $runtime run --rm --network=host \
        -e "SERVER_ENDPOINT=$server_endpoint" \
        -e "ACCESS_KEY=$RUCKET_ACCESS_KEY" \
        -e "SECRET_KEY=$RUCKET_SECRET_KEY" \
        -e "ENABLE_HTTPS=$is_https" \
        -e "MINT_MODE=core" \
        -v "$mint_log_dir:/mint/log" \
        minio/mint:latest > "$log_file" 2>&1; then
        log_success "MinIO Mint completed successfully"
    else
        exit_code=$?
        if [[ $exit_code -eq 124 ]]; then
            log_error "MinIO Mint timed out after 30 minutes"
        else
            log_warn "MinIO Mint completed with exit code: $exit_code"
        fi
    fi

    # Copy results
    if [[ -f "$mint_log_dir/log.json" ]]; then
        cp "$mint_log_dir/log.json" "$results_file"
        log_info "Results saved to $results_file"
    else
        # Create a minimal results file
        echo '{"error": "No results file generated", "tests": []}' > "$results_file"
        log_warn "No results file generated by mint"
    fi

    # Parse and display summary
    if command -v jq &> /dev/null && [[ -f "$results_file" ]]; then
        local passed failed na total
        passed=$(jq -s '[.[] | select(.status == "PASS")] | length' "$results_file" 2>/dev/null || echo "0")
        failed=$(jq -s '[.[] | select(.status == "FAIL")] | length' "$results_file" 2>/dev/null || echo "0")
        na=$(jq -s '[.[] | select(.status == "NA")] | length' "$results_file" 2>/dev/null || echo "0")
        total=$((passed + failed + na))

        echo ""
        log_info "============================================"
        log_info "S3 Compatibility Test Results"
        log_info "============================================"
        log_info "Total:   $total tests"
        log_success "Passed:  $passed"
        if [[ "$failed" -gt 0 ]]; then
            log_error "Failed:  $failed"
        else
            log_info "Failed:  $failed"
        fi
        log_info "N/A:     $na"
        echo ""

        # Calculate compatibility percentage
        if [[ $total -gt 0 ]]; then
            local compat_pct=$((passed * 100 / total))
            log_info "Compatibility: ${compat_pct}%"
        fi

        # Show failed tests
        if [[ "$failed" -gt 0 ]]; then
            echo ""
            log_warn "Failed tests:"
            jq -rs '.[] | select(.status == "FAIL") | "  [\(.function)] \(.name // "unknown")"' "$results_file" 2>/dev/null | head -20 || true
        fi
    else
        log_warn "Install 'jq' for detailed test results parsing"
    fi

    # Cleanup
    rm -rf "$mint_log_dir"

    log_info ""
    log_info "Full log: $log_file"
    log_info "Results:  $results_file"

    return $exit_code
}

generate_summary() {
    local report_file="$REPORTS_DIR/summary.md"
    local timestamp
    timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
    local results_file="$REPORTS_DIR/mint-results.json"

    cat > "$report_file" << EOF
# S3 Compatibility Test Summary

**Date:** $timestamp
**Endpoint:** $RUCKET_ENDPOINT
**Test Suite:** MinIO Mint

## Results

EOF

    if [[ -f "$results_file" ]] && command -v jq &> /dev/null; then
        local passed failed na
        passed=$(jq -s '[.[] | select(.status == "PASS")] | length' "$results_file" 2>/dev/null || echo "0")
        failed=$(jq -s '[.[] | select(.status == "FAIL")] | length' "$results_file" 2>/dev/null || echo "0")
        na=$(jq -s '[.[] | select(.status == "NA")] | length' "$results_file" 2>/dev/null || echo "0")

        cat >> "$report_file" << EOF
| Status | Count |
|--------|-------|
| Passed | $passed |
| Failed | $failed |
| N/A    | $na |

EOF

        if [[ "$failed" -gt 0 ]]; then
            echo "## Failed Tests" >> "$report_file"
            echo "" >> "$report_file"
            jq -rs '.[] | select(.status == "FAIL") | "- **\(.function)**: \(.name // "unknown") - \(.error // "no error message")"' "$results_file" 2>/dev/null >> "$report_file" || true
        fi
    else
        echo "See mint-results.json for details" >> "$report_file"
    fi

    log_info "Summary saved to $report_file"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -e|--endpoint)
            RUCKET_ENDPOINT="$2"
            shift 2
            ;;
        -a|--access-key)
            RUCKET_ACCESS_KEY="$2"
            shift 2
            ;;
        -s|--secret-key)
            RUCKET_SECRET_KEY="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            ;;
    esac
done

# Main execution
log_info "S3 Compatibility Test Runner (MinIO Mint)"
log_info "=========================================="

check_dependencies
setup_directories
check_rucket_running
run_mint_tests
generate_summary

log_success "Tests completed! Reports saved to $REPORTS_DIR"
