#!/usr/bin/env bash
# Copyright 2026 Rucket Dev
# SPDX-License-Identifier: Apache-2.0

# MinIO Mint Runner
# This script runs minio/mint tests against Rucket using Docker/Podman

set -euo pipefail

MINT_IMAGE="minio/mint:latest"

# Detect container runtime (prefer podman, fallback to docker)
get_container_runtime() {
    if command -v podman &> /dev/null; then
        echo "podman"
    elif command -v docker &> /dev/null; then
        echo "docker"
    else
        log_error "Neither podman nor docker found"
        exit 1
    fi
}

mint_run() {
    local endpoint="$1"
    local access_key="$2"
    local secret_key="$3"
    local reports_dir="$4"

    local runtime
    runtime=$(get_container_runtime)
    log_info "Using container runtime: $runtime"

    local results_file="$reports_dir/mint-results.json"
    local log_file="$reports_dir/mint-tests.log"

    # Parse endpoint
    local server_endpoint is_https
    if [[ "$endpoint" =~ ^https:// ]]; then
        is_https="1"
        server_endpoint="${endpoint#https://}"
    else
        is_https="0"
        server_endpoint="${endpoint#http://}"
    fi

    # Pull latest mint image
    log_info "Pulling minio/mint image..."
    $runtime pull "$MINT_IMAGE" 2>/dev/null || true

    log_info "Running minio/mint tests..."
    log_info "Endpoint: $server_endpoint (HTTPS: $is_https)"

    # Create a temporary directory for logs
    local mint_log_dir
    mint_log_dir=$(mktemp -d)

    # Run mint container
    # Note: We use --network=host to access localhost endpoints
    local container_args=(
        "run"
        "--rm"
        "--network=host"
        "-e" "SERVER_ENDPOINT=$server_endpoint"
        "-e" "ACCESS_KEY=$access_key"
        "-e" "SECRET_KEY=$secret_key"
        "-e" "ENABLE_HTTPS=$is_https"
        "-e" "MINT_MODE=core"  # Run core tests only for faster results
        "-v" "$mint_log_dir:/mint/log"
        "$MINT_IMAGE"
    )

    # Run with timeout
    local exit_code=0
    if timeout 1800 $runtime "${container_args[@]}" > "$log_file" 2>&1; then
        log_success "minio/mint completed successfully"
    else
        exit_code=$?
        if [[ $exit_code -eq 124 ]]; then
            log_error "minio/mint timed out after 30 minutes"
        else
            log_warn "minio/mint completed with exit code: $exit_code"
        fi
    fi

    # Copy results
    if [[ -f "$mint_log_dir/log.json" ]]; then
        cp "$mint_log_dir/log.json" "$results_file"
        log_info "Results saved to $results_file"
    else
        # Create a minimal results file
        echo '{"error": "No results file generated", "tests": []}' > "$results_file"
        log_warn "No results file generated by mint"
    fi

    # Parse and display summary
    if command -v jq &> /dev/null && [[ -f "$results_file" ]]; then
        local passed failed na
        passed=$(jq -s '[.[] | select(.status == "PASS")] | length' "$results_file" 2>/dev/null || echo "0")
        failed=$(jq -s '[.[] | select(.status == "FAIL")] | length' "$results_file" 2>/dev/null || echo "0")
        na=$(jq -s '[.[] | select(.status == "NA")] | length' "$results_file" 2>/dev/null || echo "0")

        log_info "Results: $passed passed, $failed failed, $na N/A"

        # Show failed tests
        if [[ "$failed" -gt 0 ]]; then
            log_warn "Failed tests:"
            jq -r '.[] | select(.status == "FAIL") | "  - \(.name): \(.error // "unknown error")"' "$results_file" 2>/dev/null | head -20 || true
        fi
    fi

    # Cleanup
    rm -rf "$mint_log_dir"

    log_info "Full log saved to $log_file"

    return $exit_code
}

# Additional helper to run specific SDK tests
mint_run_sdk() {
    local endpoint="$1"
    local access_key="$2"
    local secret_key="$3"
    local sdk="$4"  # e.g., "aws-sdk-go", "minio-java", etc.
    local reports_dir="$5"

    local runtime
    runtime=$(get_container_runtime)

    local server_endpoint is_https
    if [[ "$endpoint" =~ ^https:// ]]; then
        is_https="1"
        server_endpoint="${endpoint#https://}"
    else
        is_https="0"
        server_endpoint="${endpoint#http://}"
    fi

    log_info "Running mint tests for SDK: $sdk"

    local mint_log_dir
    mint_log_dir=$(mktemp -d)

    $runtime run --rm --network=host \
        -e "SERVER_ENDPOINT=$server_endpoint" \
        -e "ACCESS_KEY=$access_key" \
        -e "SECRET_KEY=$secret_key" \
        -e "ENABLE_HTTPS=$is_https" \
        -e "MINT_MODE=core" \
        -v "$mint_log_dir:/mint/log" \
        "$MINT_IMAGE" "$sdk"

    if [[ -f "$mint_log_dir/log.json" ]]; then
        cp "$mint_log_dir/log.json" "$reports_dir/mint-$sdk-results.json"
    fi

    rm -rf "$mint_log_dir"
}
